# Generated by Django 5.2.8 on 2025-12-16 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qna", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.TextField(help_text="답변 내용 본문")),
                ("is_adopted", models.BooleanField(default=False, help_text="채택 여부")),
                (
                    "author",
                    models.ForeignKey(
                        help_text="답변 작성자 ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        help_text="답변이 속한 질문 ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="qna.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "답변",
                "verbose_name_plural": "답변 목록",
                "db_table": "answers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnswerComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.CharField(help_text="댓글 내용 본문", max_length=500)),
                (
                    "answer",
                    models.ForeignKey(
                        help_text="댓글이 달린 답변 ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answer_comments",
                        to="qna.answer",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="댓글 작성자 ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "답변 댓글",
                "verbose_name_plural": "답변 댓글 목록",
                "db_table": "answers_comments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnswerImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image_url", models.CharField(help_text="이미지 파일 경로 URL", max_length=255)),
                (
                    "answer",
                    models.ForeignKey(
                        blank=True,
                        help_text="이미지가 속한 답변 ID",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="qna.answer",
                    ),
                ),
            ],
            options={
                "verbose_name": "답변 이미지",
                "verbose_name_plural": "답변 이미지 목록",
                "db_table": "answers_images",
                "ordering": ["-created_at"],
            },
        ),
    ]
