# Generated by Django 5.2.8 on 2025-12-17 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qna", "0002_answer_answercomment_answerimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answerimage",
            name="answer",
            field=models.ForeignKey(
                default=1,
                help_text="이미지가 속한 답변 ID",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="qna.answer",
            ),
            preserve_default=False,
        ),
    ]
