# Generated by Django 5.2.8 on 2025-12-19 03:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qna", "0003_alter_answerimage_answer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="answercomment",
            name="answer",
            field=models.ForeignKey(
                help_text="댓글이 달린 답변 ID",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="qna.answer",
            ),
        ),
        migrations.AlterField(
            model_name="answercomment",
            name="author",
            field=models.ForeignKey(
                help_text="댓글 작성자 ID",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answer_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="answerimage",
            name="image_url",
            field=models.CharField(
                db_index=True,
                help_text="이미지 파일 경로 URL",
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        message="이미지 경로는 반드시 'answer_images/'로 시작하는 S3 Key여야 합니다",
                        regex="^answer_images/",
                    )
                ],
            ),
        ),
    ]
