# Generated by Django 5.2.8 on 2025-12-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qna", "0004_alter_answercomment_answer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answerimage",
            name="image_url",
            field=models.CharField(help_text="S3 object Key", max_length=500),
        ),
    ]
