# Generated by Django 5.2.8 on 2025-12-19 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qna", "0005_alter_answerimage_image_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answer",
            options={},
        ),
        migrations.AlterModelOptions(
            name="answercomment",
            options={},
        ),
        migrations.AlterModelOptions(
            name="answerimage",
            options={},
        ),
        migrations.AlterModelTable(
            name="answercomment",
            table="answer_comments",
        ),
        migrations.AlterModelTable(
            name="answerimage",
            table="answer_images",
        ),
    ]
