# Generated by Django 5.2.8 on 2025-12-31 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qna", "0006_alter_answer_options_alter_answercomment_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="questioncategory",
            options={"verbose_name": "질의응답 카테고리", "verbose_name_plural": "질의응답 카테고리 목록"},
        ),
        migrations.AddField(
            model_name="questioncategory",
            name="type",
            field=models.CharField(
                choices=[("large", "대분류"), ("medium", "중분류"), ("small", "소분류")],
                default="large",
                max_length=10,
                verbose_name="카테고리 종류",
            ),
        ),
        migrations.AlterField(
            model_name="questioncategory",
            name="name",
            field=models.CharField(max_length=50, verbose_name="카테고리 이름"),
        ),
        migrations.AlterField(
            model_name="questioncategory",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="qna.questioncategory",
                verbose_name="부모 카테고리",
            ),
        ),
    ]
