# Generated by Django 5.2.8 on 2026-01-02 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qna", "0007_alter_questioncategory_options_questioncategory_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={"verbose_name": "질의응답", "verbose_name_plural": "질의응답 목록"},
        ),
    ]
