# Generated by Django 5.2.8 on 2026-01-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qna", "0008_alter_question_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionaianswer",
            name="using_model",
            field=models.CharField(
                choices=[("gemini-2.5-flash", "gemini"), ("openai-o4-mini", "openai")], max_length=20
            ),
        ),
    ]
