# Generated by Django 5.2.8 on 2025-12-10 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_cohort_delete_cohorts_and_more"),
        ("user", "0002_rename_phone_num_user_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentenrollmentrequest",
            name="cohort",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="courses.cohort"),
        ),
    ]
