# Generated by Django 5.2.8 on 2025-12-15 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_cohortstudent_learningcoach_operationmanager_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentenrollmentrequest",
            name="status",
            field=models.CharField(
                choices=[("PENDING", "Pending"), ("IN_PROGRESS", "In Progress"), ("COMPLETED", "Completed")],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="withdrawal",
            name="reason",
            field=models.CharField(
                choices=[
                    ("GRADUATION", "졸업 및 수료"),
                    ("TRANSFER", "편입 및 전학"),
                    ("NO_LONGER_NEEDED", "더 이상 필요하지 않음"),
                    ("SERVICE_DISSATISFACTION", "서비스 불만족"),
                    ("PRIVACY_CONCERN", "개인정보 보호 우려"),
                    ("OTHER", "기타"),
                ],
                max_length=30,
            ),
        ),
    ]
