# Generated by Django 5.2.8 on 2025-12-17 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_studentenrollmentrequest_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentenrollmentrequest",
            name="accepted_at",
            field=models.DateTimeField(null=True),
        ),
    ]
