# Generated by Django 5.2.8 on 2025-12-30 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_alter_subject_status"),
        ("user", "0005_alter_studentenrollmentrequest_accepted_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cohortstudent",
            name="cohort",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="cohortstudent", to="courses.cohort"
            ),
        ),
        migrations.AlterField(
            model_name="studentenrollmentrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ACCEPTED", "Accepted"),
                    ("REJECTED", "Rejected"),
                    ("CANCELED", "Canceled"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
