# Generated by Django 5.2.8 on 2025-12-09 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=30)),
                ("number_of_days", models.SmallIntegerField(max_length=2)),
                ("number_of_hours", models.SmallIntegerField(max_length=3)),
                ("thumbnail_img_url", models.URLField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(choices=[("active", "Activated"), ("deactivated", "Deactivated")], max_length=11),
                ),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                ("course_id", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="courses.course")),
            ],
            options={
                "db_table": "Subjects",
            },
        ),
    ]
