# Generated by Django 5.2.8 on 2025-12-10 02:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_subject"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Cohorts",
        ),
        migrations.CreateModel(
            name="Cohort",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ("max_student", models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ("end_date", models.DateTimeField()),
                ("start_date", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "대기중"), ("IN_PROGRESS", "수강중"), ("COMPLETED", "수료")],
                        default="PENDING",
                    ),
                ),
            ],
            options={
                "db_table": "cohorts",
            },
        ),
        migrations.RenameField(
            model_name="subject",
            old_name="course_id",
            new_name="course",
        ),
        migrations.RenameField(
            model_name="subject",
            old_name="create_at",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="subject",
            old_name="update_at",
            new_name="updated_at",
        ),
        migrations.AddField(
            model_name="course",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="subject",
            name="number_of_days",
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="subject",
            name="number_of_hours",
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="subject",
            name="status",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="subject",
            name="title",
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterModelTable(
            name="subject",
            table="subjects",
        ),
        migrations.AddField(
            model_name="cohort",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="cohorts", to="courses.course"
            ),
        ),
        migrations.AddConstraint(
            model_name="cohort",
            constraint=models.CheckConstraint(condition=models.Q(("number__gte", 1)), name="number_non_negative"),
        ),
        migrations.AddConstraint(
            model_name="cohort",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_student__gte", 1)), name="max_student_non_negative"
            ),
        ),
    ]
