# Generated by Django 5.2.8 on 2025-12-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_cohort_delete_cohorts_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="create_at",
        ),
        migrations.RemoveField(
            model_name="course",
            name="update_at",
        ),
        migrations.AlterField(
            model_name="cohort",
            name="end_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="cohort",
            name="start_date",
            field=models.DateField(),
        ),
    ]
