# Generated by Django 5.2.8 on 2025-12-17 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_remove_course_create_at_remove_course_update_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cohort",
            options={"verbose_name": "Cohort", "verbose_name_plural": "Cohorts"},
        ),
        migrations.AlterModelOptions(
            name="course",
            options={"verbose_name": "Course", "verbose_name_plural": "Courses"},
        ),
    ]
