# Generated by Django 5.2.8 on 2025-12-18 09:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_alter_cohort_options_alter_course_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subject",
            options={"verbose_name": "Subject", "verbose_name_plural": "Subjects"},
        ),
        migrations.AlterField(
            model_name="subject",
            name="number_of_days",
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name="subject",
            name="number_of_hours",
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddConstraint(
            model_name="subject",
            constraint=models.CheckConstraint(
                condition=models.Q(("number_of_days__gte", 1)), name="number_of_days_non_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="subject",
            constraint=models.CheckConstraint(
                condition=models.Q(("number_of_hours__gte", 1)), name="number_of_hours_non_negative"
            ),
        ),
    ]
