# Generated by Django 5.2.8 on 2025-12-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_alter_subject_options_alter_subject_number_of_days_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="status",
            field=models.CharField(
                choices=[("activated", "Activated"), ("deactivated", "Deactivated")], default="deactivated"
            ),
        ),
    ]
