# Generated by Django 5.2.8 on 2025-12-16 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("qna", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatbotSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=30)),
                (
                    "using_model",
                    models.CharField(choices=[("gemini", "GEMINI 2.7"), ("openai", "OPENAI 4.7")], max_length=16),
                ),
                ("question", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="qna.question")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "chatbot_sessions",
                "ordering": ("-created_at", "-id"),
                "constraints": [models.UniqueConstraint(fields=("user", "question"), name="user_question_unique")],
            },
        ),
    ]
