# Generated by Django 5.2.8 on 2026-01-04 15:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
        ("qna", "0008_alter_question_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatbotsession",
            name="using_model",
            field=models.CharField(
                choices=[("gemini-2.5-flash", "Gemini"), ("openai-o4-mini", "Openai")], max_length=20
            ),
        ),
        migrations.AddConstraint(
            model_name="chatbotsession",
            constraint=models.UniqueConstraint(fields=("user", "question"), name="user_question_unique"),
        ),
    ]
