# Generated by Django 5.2.8 on 2025-12-31 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0002_alter_chatbotsession_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatbotsession",
            name="using_model",
            field=models.CharField(
                choices=[("gemini-2.5-flash", "gemini"), ("openai-o4-mini", "openai")], max_length=20
            ),
        ),
    ]
