# Generated by Django 5.2.9 on 2025-12-10 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0003_cohort_delete_cohorts_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=50)),
                ("thumbnail_img_url", models.CharField(default="default_img_url", max_length=255)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="exams", to="courses.subject"
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam",
                "verbose_name_plural": "Exams",
                "db_table": "exams",
            },
        ),
        migrations.CreateModel(
            name="ExamDeployment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("duration_time", models.PositiveSmallIntegerField(default=60, help_text="시험 진행 시간 (분 단위)")),
                ("access_code", models.CharField(help_text="Base62 인코딩된 참가 코드", max_length=64, unique=True)),
                ("open_at", models.DateTimeField()),
                ("close_at", models.DateTimeField()),
                (
                    "questions_snapshot",
                    models.JSONField(
                        db_column="questions_snapshot_json", help_text="배포 시점의 시험 문항 스냅샷(JSON)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("activated", "활성화"), ("deactivated", "비활성화")],
                        default="activated",
                        max_length=32,
                    ),
                ),
                (
                    "cohort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exam_deployments",
                        to="courses.cohort",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="deployments", to="exams.exam"
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam Deployment",
                "verbose_name_plural": "Exam Deployments",
                "db_table": "exam_deployments",
            },
        ),
        migrations.CreateModel(
            name="ExamQuestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("question", models.CharField(max_length=255)),
                ("prompt", models.TextField(blank=True, null=True)),
                (
                    "blank_count",
                    models.PositiveSmallIntegerField(blank=True, help_text="빈칸 채우기 문제의 빈칸 개수", null=True),
                ),
                (
                    "options",
                    models.JSONField(
                        blank=True, db_column="options_json", help_text="객관식/순서정렬/OX 선택지 리스트", null=True
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("single_choice", "단일 선택"),
                            ("multiple_choice", "다중 선택"),
                            ("ox", "O/X"),
                            ("short_answer", "단답형"),
                            ("ordering", "순서 정렬"),
                            ("fill_blank", "빈칸 채우기"),
                        ],
                        max_length=32,
                    ),
                ),
                ("answer", models.JSONField(help_text="정답 표현 (문제 유형에 따라 문자열/리스트 등)")),
                ("point", models.PositiveSmallIntegerField()),
                ("explanation", models.TextField(blank=True, null=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="questions", to="exams.exam"
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam Question",
                "verbose_name_plural": "Exam Questions",
                "db_table": "exam_questions",
            },
        ),
        migrations.CreateModel(
            name="ExamSubmission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField()),
                ("cheating_count", models.PositiveSmallIntegerField(default=0)),
                ("answers", models.JSONField(db_column="answers_json", help_text="제출한 답안 전체(JSON)")),
                ("score", models.PositiveSmallIntegerField()),
                ("correct_answer_count", models.PositiveSmallIntegerField()),
                (
                    "deployment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="exams.examdeployment",
                    ),
                ),
                (
                    "submitter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam Submission",
                "verbose_name_plural": "Exam Submissions",
                "db_table": "exam_submissions",
                "indexes": [models.Index(fields=["deployment", "submitter"], name="exam_submis_deploym_86a49d_idx")],
            },
        ),
    ]
