# Generated by Django 5.2.8 on 2025-12-18 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examquestion",
            name="explanation",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
