# Generated by Django 5.2.8 on 2025-12-31 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0002_alter_examquestion_explanation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examquestion",
            name="explanation",
            field=models.TextField(blank=True, default=""),
        ),
    ]
