# Generated by Django 5.2.8 on 2025-12-17 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"verbose_name": "Post", "verbose_name_plural": "Posts"},
        ),
        migrations.AlterModelOptions(
            name="postcategory",
            options={"verbose_name": "Post Category", "verbose_name_plural": "Post Category"},
        ),
        migrations.AlterModelOptions(
            name="postlike",
            options={"verbose_name": "Post Like", "verbose_name_plural": "Post Like"},
        ),
        migrations.AlterField(
            model_name="postcomment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="post_comments", to="community.post"
            ),
        ),
        migrations.AlterField(
            model_name="postimage",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="post_images", to="community.post"
            ),
        ),
        migrations.AlterField(
            model_name="postlike",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="post_likes", to="community.post"
            ),
        ),
    ]
