# Generated by Django 5.2.8 on 2025-12-12 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="postcategory",
            options={"verbose_name": "Post Category", "verbose_name_plural": "Post Category"},
        ),
    ]
